version: "2"
services:
    sv-backend-report:
        container_name: sv_backend_report
        build: .
        environment:
            - PORT=5000
            - POSTGRES_URI=postgres://admin:admin@postgresql:5432/b2c
            - POSTGRES_URI_TEST=postgres://admin:admin@postgresql:5432/b2c-test
            - MONGO_URI=mongodb://mongo:27017/b2c-event?authSource=admin
            - MONGO_URI_TEST=mongodb://mongo:27017/b2c-event-test?authSource=admin
            - RABBITMQ_URI=amqp://rabbitmq:5672
            - REDIS_URI=redis://redis:6379
            - MANAGER_SERVICE_URL=https://sv_backend_manager
        user: "1000:1000"
        volumes:
            - .:/app  
        ports:
            - "5005:5000"
        external_links:
            - mongodb
        networks:
            - docker_sv_backend_common
networks:
    docker_sv_backend_common:
        external: true
